import React,{useEffect,useState} from 'react';
import {Building2,Plus,MapPin,ArrowRight,CalendarDays,Users,GraduationCap,X,ShieldCheck} from 'lucide-react';
import {Campus,Examination} from '../types/tenant';
import {createCampus,createExamination,setSelectedCampus} from '../lib/tenant';
import {migrateLegacyDataToCampus} from '../lib/realtime';
interface Props{uid:string;campuses:Campus[];exams:Examination[];selectedCampus:Campus|null;onCampusSelected:(c:Campus|null)=>void;onRefresh:()=>void;onOpenExam:(e:Examination)=>void;onSignOut:()=>void;}
const initialCampus={name:'',code:'',place:'',district:'',state:'',country:'India',address:'',phone:'',email:''};
export const CampusHome:React.FC<Props>=({uid,campuses,selectedCampus,onCampusSelected,onOpenExam,onSignOut})=>{
 const [show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const [form,setForm]=useState(initialCampus);
 const restore=async(c:Campus)=>{setSelectedCampus(c.id);try{await migrateLegacyDataToCampus(c.id)}catch(e){console.warn('Legacy restore skipped:',e)}onCampusSelected(c)};
 useEffect(()=>{if(selectedCampus)restore(selectedCampus)},[selectedCampus?.id]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const c=await createCampus(uid,form);await restore(c);setShow(false);setForm(initialCampus)}catch(err:any){setError(err?.message||'Could not create campus.')}finally{setBusy(false)}};
 if(selectedCampus)return <div className="examio-page"><div className="examio-hero"><div><div className="examio-eyebrow">CAMPUS</div><h1>{selectedCampus.name}</h1><p>{[selectedCampus.place,selectedCampus.district,selectedCampus.state].filter(Boolean).join(' · ')||'Campus management'}</p></div><button className="examio-primary" onClick={()=>onOpenExam({} as Examination)}><CalendarDays/> Open examinations</button></div><div className="examio-campus-banner"><div className="examio-campus-emblem"><ShieldCheck/></div><div><strong>{selectedCampus.name}</strong><span>{selectedCampus.code||'Campus account'} · Permanent campus data</span></div><button onClick={()=>onCampusSelected(null)}>My campuses <ArrowRight/></button></div><div className="examio-statrow"><div><span>STUDENTS</span><strong>Permanent data</strong></div><div><span>CLASSES & SUBJECTS</span><strong>Campus setup</strong></div><div><span>EXAMINATIONS</span><strong>Managed separately</strong></div></div><div className="examio-section-title"><div><h2>Campus workspace</h2><p>Set up permanent campus data once, then reuse it across examinations.</p></div></div><div className="examio-grid"><Info icon={GraduationCap} title="Classes" text="Create classes once and reuse them in every examination."/><Info icon={Users} title="Students" text="Maintain the permanent student register for this campus."/><Info icon={CalendarDays} title="Examinations" text="Create multiple examinations throughout the academic year."/></div></div>;
 return <div className="examio-page"><div className="examio-hero"><div><div className="examio-eyebrow">EXAMIO ACCOUNT</div><h1>My campuses</h1><p>Manage multiple campuses and keep their permanent data separate.</p></div><button className="examio-primary" onClick={()=>setShow(true)}><Plus/> Create campus</button></div><div className="examio-grid">{campuses.map(c=><button key={c.id} className="examio-campus-card" onClick={()=>restore(c)}><div className="examio-campus-logo"><Building2/></div><div><h3>{c.name}</h3><p><MapPin/> {[c.place,c.district,c.state].filter(Boolean).join(', ')||'Location not specified'}</p></div><ArrowRight className="examio-campus-arrow"/></button>)}{!campuses.length&&<div className="examio-empty"><Building2/><h3>No campus yet</h3><p>Create your first campus to begin.</p><button className="examio-primary" onClick={()=>setShow(true)}><Plus/> Create campus</button></div>}</div>{show&&<div className="examio-modal"><div className="examio-modal-card"><div className="examio-modal-head"><div><div className="examio-eyebrow">CAMPUS SETUP</div><h2>Create campus</h2></div><button onClick={()=>setShow(false)}><X/></button></div>{error&&<div className="examio-error">{error}</div>}<form className="examio-form" onSubmit={submit}>{Object.entries(form).map(([key,value])=><label key={key}>{key==='name'?'Campus name *':key.charAt(0).toUpperCase()+key.slice(1)}<input required={key==='name'||key==='place'} type={key==='email'?'email':'text'} value={value} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<button disabled={busy} className="examio-primary">{busy?'Creating…':'Create campus'}</button></form></div></div>}</div>;
};
const Info=({icon:Icon,title,text}:{icon:any;title:string;text:string})=><div className="examio-info-card"><div className="examio-icon"><Icon/></div><h3>{title}</h3><p>{text}</p><span>Manage <ArrowRight/></span></div>;
