import React from 'react';
import { FolderTree, GraduationCap, Users, Calendar, ArrowRight, BookOpen, ClipboardList } from 'lucide-react';
import { Category, ClassItem, Student, ExamSession, Subject, AbsenteeRecord } from '../types';

interface DashboardViewProps {
  categories: Category[]; classes: ClassItem[]; students: Student[]; sessions: ExamSession[];
  subjects?: Subject[]; absenteeRecords?: AbsenteeRecord[];
  onNavigate: (tab: any) => void; onSelectSessionForGenerator: (sessionId: string) => void;
}

export const DashboardView: React.FC<DashboardViewProps> = ({ categories, classes, students, sessions, subjects = [], absenteeRecords = [], onNavigate, onSelectSessionForGenerator }) => {
  const todayStr = new Date().toISOString().split('T')[0];
  const todaysSessions = sessions.filter(s => s.date === todayStr);
  const todaysAbsentees = absenteeRecords.filter(r => r.date === todayStr);
  const cards = [
    {label:'Total Categories',value:categories.length,icon:FolderTree,tab:'categories',color:'bg-blue-500/10 text-blue-600 border-blue-200'},
    {label:'Total Classes',value:classes.length,icon:GraduationCap,tab:'classes',color:'bg-indigo-500/10 text-indigo-600 border-indigo-200'},
    {label:'Total Students',value:students.length,icon:Users,tab:'students',color:'bg-emerald-500/10 text-emerald-600 border-emerald-200'},
    {label:'Total Subjects',value:subjects.length,icon:BookOpen,tab:'subjects',color:'bg-violet-500/10 text-violet-600 border-violet-200'},
    {label:"Today's Absentees",value:todaysAbsentees.length,icon:ClipboardList,tab:'absentees',color:'bg-rose-500/10 text-rose-600 border-rose-200'},
    {label:'Total Absentee Records',value:absenteeRecords.length,icon:ClipboardList,tab:'reports',color:'bg-orange-500/10 text-orange-600 border-orange-200'},
    {label:'Total Examinations',value:'—',icon:Calendar,tab:'examinations',color:'bg-purple-500/10 text-purple-600 border-purple-200'},
    {label:'Total Sessions',value:sessions.length,icon:Calendar,tab:'timetable',color:'bg-amber-500/10 text-amber-600 border-amber-200'},
  ];
  return <div className="space-y-6">
    <div className="bg-slate-900 rounded-lg p-5 text-white shadow-xs border border-slate-800 flex flex-col md:flex-row items-start md:items-center justify-between gap-4"><div><span className="inline-block px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider bg-orange-500 text-white mb-2">Noorul Huda Board</span><h2 className="text-lg font-bold tracking-tight">Examio — Examination & Absentee Dashboard</h2><p className="text-slate-400 text-xs mt-1">Manage student registers, absentee records, reports and examination seating from one system.</p></div><button onClick={()=>onNavigate('absentees')} className="px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold rounded shadow-xs flex items-center transition shrink-0"><ClipboardList className="w-3.5 h-3.5 mr-2"/>Record Absentees</button></div>
    <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">{cards.map((card,idx)=>{const Icon=card.icon;return <div key={idx} onClick={()=>onNavigate(card.tab)} className="bg-white p-4 border border-slate-200 rounded-lg shadow-2xs hover:shadow-xs transition cursor-pointer group"><div className="flex items-center justify-between"><span className="text-[10px] uppercase font-bold text-slate-400 tracking-wider">{card.label}</span><div className={`p-1.5 rounded border ${card.color}`}><Icon className="w-3.5 h-3.5"/></div></div><div className="mt-2 flex items-baseline justify-between"><span className="text-2xl font-bold text-slate-800 tracking-tight">{typeof card.value==='number'?card.value.toLocaleString():card.value}</span><ArrowRight className="w-4 h-4 text-slate-300 group-hover:text-blue-600 transition"/></div></div>})}</div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <div className="lg:col-span-2 bg-white rounded-lg border border-slate-200 p-5 shadow-2xs"><div className="flex items-center justify-between pb-3 border-b border-slate-100"><div><h3 className="text-sm font-bold text-slate-800">Today's Absentee Summary</h3><p className="text-xs text-slate-500">{todayStr}</p></div><button onClick={()=>onNavigate('absentees')} className="text-xs text-blue-600 font-bold hover:underline">Open Entry →</button></div><div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-3">{todaysAbsentees.length===0?<div className="md:col-span-2 text-center py-8 text-slate-400 text-xs bg-slate-50 rounded border border-dashed border-slate-200">No absentee records entered today.</div>:Object.entries(todaysAbsentees.reduce((acc,r)=>{acc[r.className]=(acc[r.className]||0)+1;return acc},{} as Record<string,number>)).map(([name,count])=><div key={name} className="flex items-center justify-between p-3 bg-slate-50 rounded-lg border border-slate-100"><span className="text-xs font-semibold">{name}</span><span className="text-sm font-bold text-rose-600">{count}</span></div>)}</div></div>
      <div className="bg-white rounded-lg border border-slate-200 p-5 shadow-2xs"><h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 border-b border-slate-100 pb-2 mb-3">Quick Workflow</h3><ul className="space-y-3 text-xs text-slate-600"><li>1. Manage Classes and Students.</li><li>2. Add Subjects once to the master list.</li><li>3. Create an examination.</li><li>4. Build that examination's timetable and rooms.</li><li>5. Generate seating, invigilation and reports.</li></ul><button onClick={()=>onNavigate('examinations')} className="w-full mt-5 py-2 bg-slate-100 hover:bg-slate-200 text-slate-800 text-xs font-bold rounded">Open Examinations</button></div>
    </div>
    <div className="bg-white rounded-lg border border-slate-200 p-5 shadow-2xs"><div className="flex items-center justify-between pb-3 border-b border-slate-100"><div><h3 className="text-sm font-bold text-slate-800">Today's Exam Sessions</h3><p className="text-xs text-slate-500">Scheduled for {todayStr}</p></div><button onClick={()=>onNavigate('examinations')} className="text-xs text-blue-600 font-bold">View Examinations →</button></div><div className="mt-4 space-y-2.5">{todaysSessions.length===0?<div className="text-center py-6 text-slate-400 text-xs bg-slate-50 rounded border border-dashed border-slate-200">No exam sessions scheduled for today.</div>:todaysSessions.map(sess=><div key={sess.id} className="p-3.5 rounded-lg border border-slate-200 bg-slate-50/60 flex items-center justify-between"><div><h4 className="text-xs font-bold text-slate-900">{sess.date} ({sess.time})</h4><p className="text-[11px] text-slate-500 mt-0.5">{sess.classConfigs.length} classes involved</p></div><button onClick={()=>onSelectSessionForGenerator(sess.id)} className="px-3 py-1.5 bg-slate-900 text-white text-xs font-semibold rounded">Allocate Seats</button></div>)}</div></div>
  </div>;
};
