import React,{useState} from 'react';
import {CalendarDays,Plus,ArrowRight,Clock3,FileText,X} from 'lucide-react';
import {Campus,Examination} from '../types/tenant';
import {createExamination} from '../lib/tenant';

interface Props{uid:string;campus:Campus;exams:Examination[];onOpen:(exam:Examination)=>void;}
const empty={name:'',academicYear:'',startDate:'',endDate:'',description:''};
export const ExaminationsView:React.FC<Props>=({uid,campus,exams,onOpen})=>{
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[form,setForm]=useState(empty);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(form.endDate<form.startDate)return setError('Ending date cannot be before starting date.');setBusy(true);try{const x=await createExamination(uid,campus.id,{...form,status:'draft'});setForm(empty);setOpen(false);onOpen(x)}catch(err:any){setError(err?.message||'Unable to create examination.')}finally{setBusy(false)}};
 return <div className="examio-page">
  <div className="examio-hero"><div><div className="examio-eyebrow">{campus.name}</div><h1>Examinations</h1><p>Create and manage every examination conducted by this campus.</p></div><button className="examio-primary" onClick={()=>{setError('');setOpen(true)}}><Plus/> Create examination</button></div>
  <div className="examio-statrow"><div><span>EXAMINATIONS</span><strong>{exams.length}</strong></div><div><span>ACTIVE CAMPUS</span><strong>{campus.name}</strong></div><div><span>WORKFLOW</span><strong>Timetable → Seating → Reports</strong></div></div>
  <div className="examio-section-title"><div><h2>Your examinations</h2><p>Select an examination to open its workspace.</p></div></div>
  <div className="examio-grid">{exams.map(ex=><button key={ex.id} onClick={()=>onOpen(ex)} className="examio-exam-card"><div className="examio-icon"><CalendarDays/></div><div className="examio-card-top"><span>{ex.status||'draft'}</span><ArrowRight/></div><h3>{ex.name}</h3><p>{ex.academicYear||'Academic year not specified'}</p><div className="examio-card-meta"><span><CalendarDays/> {ex.startDate}</span><span>→</span><span>{ex.endDate}</span></div><div className="examio-card-footer"><Clock3/> Examination workspace</div></button>)}{!exams.length&&<div className="examio-empty"><FileText/><h3>No examinations yet</h3><p>Create the first examination for {campus.name}.</p><button onClick={()=>setOpen(true)} className="examio-primary"><Plus/> Create examination</button></div>}</div>
  {open&&<div className="examio-modal"><div className="examio-modal-card"><div className="examio-modal-head"><div><div className="examio-eyebrow">NEW EXAMINATION</div><h2>Create examination</h2></div><button onClick={()=>setOpen(false)}><X/></button></div>{error&&<div className="examio-error">{error}</div>}<form onSubmit={submit} className="examio-form"><label>Examination name *<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Mid-Term Examination 2026"/></label><div className="examio-two"><label>Academic year<input value={form.academicYear} onChange={e=>setForm({...form,academicYear:e.target.value})} placeholder="2026–27"/></label><label>Starting date *<input required type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label></div><label>Ending date *<input required type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></label><label>Description<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Optional notes about this examination"/></label><button disabled={busy} className="examio-primary examio-submit">{busy?'Creating…':'Create examination'}</button></form></div></div>}
 </div>;
};
