import React,{useEffect,useMemo,useState} from 'react';
import {CalendarDays,ClipboardList,Grid3X3,Users,BarChart3,Plus,Trash2,ArrowLeft,CheckCircle2,LayoutDashboard} from 'lucide-react';
import {Campus,Examination,ExamTimetableEntry} from '../types/tenant';
import {deleteTimetableEntry,saveTimetableEntry,subscribeTimetable} from '../lib/tenant';
import {Category,ClassItem,Subject,Student,Room,SeatingArrangement,ExamSession} from '../types';
import {SeatingGeneratorView} from './SeatingGeneratorView';
import './ExaminationWorkspace.css';
interface Props{uid:string;campus:Campus;exam:Examination;categories:Category[];classes:ClassItem[];subjects:Subject[];students:Student[];rooms:Room[];arrangements:SeatingArrangement[];onSaveArrangement:(x:SeatingArrangement)=>Promise<void>;onOpenPrintModal:(type:'roomDiagram'|'studentList',session:ExamSession,arrangement:SeatingArrangement)=>void;onBack:()=>void;}
type Tab='overview'|'timetable'|'attendance'|'seating'|'duty'|'reports';
export const ExaminationWorkspace:React.FC<Props>=({uid,campus,exam,categories,classes,subjects,students,rooms,arrangements,onSaveArrangement,onOpenPrintModal,onBack})=>{
 const [entries,setEntries]=useState<ExamTimetableEntry[]>([]),[date,setDate]=useState(exam.startDate||''),[classId,setClassId]=useState(''),[subjectId,setSubjectId]=useState(''),[startTime,setStartTime]=useState('09:00'),[endTime,setEndTime]=useState('11:00'),[tab,setTab]=useState<Tab>('overview'),[error,setError]=useState('');
 useEffect(()=>{if(!exam?.id)return;const unsub=subscribeTimetable(uid,campus.id,exam.id,x=>setEntries(Array.isArray(x)?x:[]));return unsub},[uid,campus.id,exam?.id]);
 const days=useMemo(()=>{if(!exam?.startDate||!exam?.endDate)return [];const out:string[]=[];const d=new Date(`${exam.startDate}T00:00:00`),end=new Date(`${exam.endDate}T00:00:00`);if(Number.isNaN(d.getTime())||Number.isNaN(end.getTime()))return out;while(d<=end&&out.length<370){out.push(d.toISOString().slice(0,10));d.setDate(d.getDate()+1)}return out},[exam.startDate,exam.endDate]);
 const className=(id:string)=>classes.find(c=>c.id===id)?.name||'Unknown class';const subjectName=(id:string)=>subjects.find(s=>s.id===id)?.name||'Unknown subject';
 const addEntry=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(!date||!classId||!subjectId)return setError('Date, class and subject are required.');if(startTime>=endTime)return setError('End time must be later than start time.');if(entries.some(x=>x.date===date&&x.classId===classId))return setError(`${className(classId)} already has an exam on ${date}.`);try{const id=crypto.randomUUID();await saveTimetableEntry(uid,campus.id,{id,examinationId:exam.id,date,classId,subjectId,startTime,endTime,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});setClassId('');setSubjectId('')}catch(err:any){setError(err?.message||'Could not save timetable entry.')}};
 const examSessions=useMemo<ExamSession[]>(()=>{const groups=new Map<string,ExamSession>();entries.forEach(x=>{const key=`${x.date}|${x.startTime||''}|${x.endTime||''}`;if(!groups.has(key))groups.set(key,{id:`${exam.id}-${x.date}-${x.startTime||'time'}`,name:`${exam.name} · ${x.date}`,date:x.date,time:`${x.startTime||''}–${x.endTime||''}`,classConfigs:[],createdAt:exam.createdAt});const s=groups.get(key)!;if(!s.classConfigs.some(c=>c.classId===x.classId))s.classConfigs.push({classId:x.classId,examMode:'Manual'});});return [...groups.values()].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))},[entries,exam.id,exam.name,exam.createdAt]);
 const tabs:[Tab,string,any][]=[['overview','Overview',BarChart3],['timetable','Timetable',CalendarDays],['attendance','Attendance',ClipboardList],['seating','Seating',Grid3X3],['duty','Invigilation',Users],['reports','Reports',BarChart3]];
 return <div className="examio-exam-page"><header className="examio-exam-header"><button className="examio-back" onClick={onBack}><ArrowLeft/></button><div className="examio-exam-title"><div className="examio-eyebrow">{campus.name}</div><h1>{exam.name||'Examination'}</h1><p>{exam.startDate||'—'} <b>→</b> {exam.endDate||'—'} <span>·</span> {exam.status||'draft'}</p></div><div className="examio-exam-badge"><CheckCircle2/> Examination workspace</div></header>
 <div className="examio-exam-layout">
  <aside className="examio-exam-sidebar">
   <div className="examio-exam-sidebar-brand"><div className="examio-exam-sidebar-mark"><LayoutDashboard/></div><div><strong>Examio</strong><span>Examination</span></div></div>
   <div className="examio-exam-sidebar-title">WORKSPACE</div>
   <nav className="examio-exam-nav">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={tab===id?'active':''}><Icon/>{label}</button>)}</nav>
   <div className="examio-exam-sidebar-footer"><button onClick={onBack}><ArrowLeft/>Back to examinations</button></div>
  </aside>
  <main className="examio-exam-content">
   <div className="examio-content-heading"><div><div className="examio-panel-kicker">EXAMINATION WORKSPACE</div><h2>{tabs.find(x=>x[0]===tab)?.[1]}</h2></div></div>
   {tab==='overview'&&<div className="examio-work-grid"><div className="examio-work-main"><div className="examio-panel"><div className="examio-panel-kicker">EXAMINATION CONTROL</div><h2>Welcome to the examination workspace</h2><p>Build the timetable first. The same timetable then drives attendance, seating, invigilation and reports.</p><div className="examio-flow"><Step n="01" title="Timetable" active={entries.length>0}/><Step n="02" title="Seating" active={examSessions.length>0}/><Step n="03" title="Invigilation" active={false}/><Step n="04" title="Reports" active={false}/></div></div></div><aside className="examio-side-stack"><Metric n={entries.length} t="Timetable entries"/><Metric n={new Set(entries.map(x=>x.classId)).size} t="Classes scheduled"/><Metric n={examSessions.length} t="Exam sessions"/></aside></div>}
   {tab==='timetable'&&<div className="examio-panel"><div className="examio-panel-kicker">SCHEDULE</div><h2>Build examination timetable</h2>{error&&<div className="examio-error">{error}</div>}<form onSubmit={addEntry} className="examio-timetable-form"><select required value={date} onChange={e=>setDate(e.target.value)}><option value="">Date</option>{days.map(d=><option key={d}>{d}</option>)}</select><select required value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select required value={subjectId} onChange={e=>setSubjectId(e.target.value)}><option value="">Subject</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input required type="time" value={startTime} onChange={e=>setStartTime(e.target.value)}/><input required type="time" value={endTime} onChange={e=>setEndTime(e.target.value)}/><button className="examio-primary"><Plus/> Add</button></form><div className="examio-table-wrap"><table><thead><tr><th>Date</th><th>Class</th><th>Subject</th><th>Time</th><th/></tr></thead><tbody>{[...entries].sort((a,b)=>`${a.date}${a.startTime}`.localeCompare(`${b.date}${b.startTime}`)).map(x=><tr key={x.id}><td>{x.date}</td><td><b>{className(x.classId)}</b></td><td>{subjectName(x.subjectId)}</td><td>{x.startTime}–{x.endTime}</td><td><button className="examio-delete" onClick={()=>deleteTimetableEntry(uid,campus.id,exam.id,x.id)}><Trash2/></button></td></tr>)}{!entries.length&&<tr><td colSpan={5} className="examio-table-empty">No timetable entries yet.</td></tr>}</tbody></table></div></div>}
   {tab==='seating'&&<div className="examio-panel"><div className="examio-panel-kicker">SEATING</div><h2>Seating generator</h2><p className="examio-muted">Sessions are created automatically from timetable entries with the same date and time.</p>{examSessions.length?<SeatingGeneratorView sessions={examSessions} students={students} classes={classes} categories={categories} rooms={rooms} arrangements={arrangements} onSaveArrangement={onSaveArrangement} onOpenPrintModal={onOpenPrintModal}/>:<div className="examio-empty"><Grid3X3/><h3>Create timetable entries first</h3><p>Once the timetable exists, seating sessions will appear here.</p></div>}</div>}
   {tab==='attendance'&&<Placeholder icon={ClipboardList} title="Attendance" text="Attendance and absentees will use the same examination timetable and permanent student register."/>}
   {tab==='duty'&&<Placeholder icon={Users} title="Invigilation" text="Invigilator assignment will use this examination's sessions and rooms."/>}
   {tab==='reports'&&<Placeholder icon={BarChart3} title="Reports" text="Reports will be generated from this examination's timetable, seating and attendance data."/>}
  </main>
 </div></div>;
};
const Metric=({n,t}:{n:number|string;t:string})=><div className="examio-metric"><strong>{n}</strong><span>{t}</span></div>;const Step=({n,title,active}:{n:string;title:string;active:boolean})=><div className={`examio-step ${active?'done':''}`}><b>{n}</b><span>{title}</span></div>;const Placeholder=({icon:Icon,title,text}:{icon:any;title:string;text:string})=><div className="examio-panel examio-placeholder"><Icon/><h2>{title}</h2><p>{text}</p></div>;
