import React,{useEffect,useMemo,useState} from 'react';
import {CalendarDays,ClipboardList,Grid3X3,Users,BarChart3,Plus,Trash2,ArrowLeft,CheckCircle2,LayoutDashboard,DoorOpen,Clock3,Info,FileText,Printer} from 'lucide-react';
import {Campus,Examination,ExamTimetableEntry} from '../types/tenant';
import {deleteTimetableEntry,saveTimetableEntry,subscribeTimetable} from '../lib/tenant';
import {Category,ClassItem,Subject,Student,Room,SeatingArrangement,ExamSession} from '../types';
import {SeatingGeneratorView} from './SeatingGeneratorView';
import {RoomsView} from './RoomsView';
import './ExaminationWorkspace.css';

interface Props{uid:string;campus:Campus;exam:Examination;categories:Category[];classes:ClassItem[];subjects:Subject[];students:Student[];rooms:Room[];arrangements:SeatingArrangement[];onSaveRoom:(room:Room)=>Promise<void>;onDeleteRoom:(id:string)=>Promise<void>;onDeleteBulkRooms?:(ids:string[])=>Promise<void>;onSaveArrangement:(x:SeatingArrangement)=>Promise<void>;onOpenPrintModal:(type:'roomDiagram'|'studentList',session:ExamSession,arrangement:SeatingArrangement)=>void;onBack:()=>void;}
type Tab='overview'|'timetable'|'rooms'|'attendance'|'seating'|'duty'|'reports';

const formatDate=(value?:string)=>{if(!value)return '—';const d=new Date(`${value}T00:00:00`);return Number.isNaN(d.getTime())?value:d.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});};
const statusMeta=(status:Examination['status'])=>({draft:{label:'Draft',cls:'examio-badge'},scheduled:{label:'Scheduled',cls:'examio-badge'},active:{label:'Ongoing',cls:'examio-badge'},completed:{label:'Completed',cls:'examio-badge'}}[status]||{label:'Draft',cls:'examio-badge'});

export const ExaminationWorkspace:React.FC<Props>=({uid,campus,exam,categories,classes,subjects,students,rooms,arrangements,onSaveRoom,onDeleteRoom,onDeleteBulkRooms,onSaveArrangement,onOpenPrintModal,onBack})=>{
 const [entries,setEntries]=useState<ExamTimetableEntry[]>([]),[date,setDate]=useState(exam.startDate||''),[classId,setClassId]=useState(''),[subjectId,setSubjectId]=useState(''),[startTime,setStartTime]=useState('09:00'),[endTime,setEndTime]=useState('11:00'),[tab,setTab]=useState<Tab>('overview'),[error,setError]=useState('');
 useEffect(()=>{if(!exam?.id)return;return subscribeTimetable(uid,campus.id,exam.id,(value:any)=>{const list=Array.isArray(value)?value:Object.values(value||{});setEntries(list as ExamTimetableEntry[])})},[uid,campus.id,exam?.id]);
 useEffect(()=>{setDate(exam.startDate||'');setClassId('');setSubjectId('');setError('')},[exam.id,exam.startDate]);
 const days=useMemo(()=>{if(!exam?.startDate||!exam?.endDate)return [];const out:string[]=[];const d=new Date(`${exam.startDate}T00:00:00`),end=new Date(`${exam.endDate}T00:00:00`);if(Number.isNaN(d.getTime())||Number.isNaN(end.getTime()))return out;while(d<=end&&out.length<370){out.push(d.toISOString().slice(0,10));d.setDate(d.getDate()+1)}return out},[exam.startDate,exam.endDate]);
 const className=(id:string)=>classes.find(c=>c.id===id)?.name||'Unknown class';
 const subjectName=(id:string)=>subjects.find(s=>s.id===id)?.name||'Unknown subject';
 const addEntry=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(!date||!classId||!subjectId)return setError('Date, class and subject are required.');if(startTime>=endTime)return setError('End time must be later than start time.');if(entries.some(x=>x.date===date&&x.classId===classId))return setError(`${className(classId)} already has an exam on ${formatDate(date)}.`);try{const now=new Date().toISOString();await saveTimetableEntry(uid,campus.id,{id:crypto.randomUUID(),examinationId:exam.id,date,classId,subjectId,startTime,endTime,createdAt:now,updatedAt:now});setClassId('');setSubjectId('')}catch(err:any){setError(err?.message||'Could not save timetable entry.')}};
 const examSessions=useMemo<ExamSession[]>(()=>{const groups=new Map<string,ExamSession>();entries.forEach(x=>{const key=`${x.date}|${x.startTime||''}|${x.endTime||''}`;if(!groups.has(key))groups.set(key,{id:`${exam.id}-${x.date}-${x.startTime||'time'}`,name:`${exam.name} · ${x.date}`,date:x.date,time:`${x.startTime||''}–${x.endTime||''}`,classConfigs:[],createdAt:exam.createdAt});const s=groups.get(key)!;if(!s.classConfigs.some(c=>c.classId===x.classId))s.classConfigs.push({classId:x.classId,examMode:'Manual'});});return [...groups.values()].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))},[entries,exam.id,exam.name,exam.createdAt]);
 const upcoming=examSessions.slice(0,6);
 const tabs:[Tab,string,any][]=[['overview','Overview',BarChart3],['timetable','Timetable',CalendarDays],['rooms','Rooms',DoorOpen],['attendance','Attendance',ClipboardList],['seating','Seating',Grid3X3],['duty','Invigilation',Users],['reports','Reports',BarChart3]];
 const activeLabel=tabs.find(x=>x[0]===tab)?.[1]||'Overview';
 return <div className="examio-exam-page">
  <header className="examio-exam-header"><button className="examio-back" onClick={onBack} aria-label="Back"><ArrowLeft/></button><div className="examio-exam-title"><div className="examio-eyebrow">{campus.name}</div><h1>{exam.name||'Examination'}</h1><p>{formatDate(exam.startDate)} <b>→</b> {formatDate(exam.endDate)} <span>·</span> {statusMeta(exam.status).label}</p></div><div className="examio-exam-badge"><CheckCircle2/> Examination workspace</div></header>
  <div className="examio-exam-layout">
   <aside className="examio-exam-sidebar">
    <div className="examio-exam-sidebar-brand"><div className="examio-exam-sidebar-mark"><LayoutDashboard/></div><div><strong>Examio</strong><span>Examination</span></div></div>
    <div className="examio-exam-sidebar-title">WORKSPACE</div>
    <nav className="examio-exam-nav">{tabs.map(([id,label,Icon])=><button type="button" key={id} onClick={()=>setTab(id)} className={tab===id?'active':''}><Icon/>{label}</button>)}</nav>
    <div className="examio-exam-sidebar-footer"><button type="button" onClick={onBack}><ArrowLeft/>Back to examinations</button></div>
   </aside>
   <main className="examio-exam-content">
    <div className="examio-content-heading"><div><div className="examio-panel-kicker">EXAMINATION WORKSPACE</div><h2>{activeLabel}</h2></div></div>

    {tab==='overview'&&<div className="space-y-5">
      <div className="examio-work-grid"><section className="examio-panel"><div className="examio-panel-kicker">CURRENT EXAMINATION</div><h2>{exam.name}</h2><p>{exam.description||'Manage the timetable, examination rooms, seating, invigilation, attendance and reports for this examination.'}</p><div className="examio-info-banner"><Info/><span>All timetable and room settings shown here belong to <strong>{exam.name}</strong> and can be different for another examination.</span></div><div className="examio-flow"><Step n="01" title="Timetable" active={entries.length>0}/><Step n="02" title="Rooms" active={rooms.length>0}/><Step n="03" title="Seating" active={arrangements.length>0}/><Step n="04" title="Reports" active={false}/></div></section><aside className="examio-side-stack"><Metric n={entries.length} t="Timetable entries"/><Metric n={rooms.length} t="Examination rooms"/><Metric n={examSessions.length} t="Exam sessions"/></aside></div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5"><section className="examio-panel"><div className="examio-panel-kicker">UPCOMING SESSIONS</div><h2>Examination schedule</h2><div className="examio-work-list">{upcoming.length?upcoming.map(s=><div className="examio-work-row" key={s.id}><div><strong>{formatDate(s.date)}</strong><span className="block mt-1"><Clock3 className="inline w-3 h-3 mr-1"/>{s.time} · {s.classConfigs.length} classes</span></div><span className="examio-badge">Scheduled</span></div>):<div className="examio-table-empty">No sessions yet. Build the timetable first.</div>}</div></section><section className="examio-panel"><div className="examio-panel-kicker">EXAMINATION SUMMARY</div><h2>At a glance</h2><div className="grid grid-cols-2 gap-3 mt-4"><Metric n={classes.length} t="Classes"/><Metric n={students.length} t="Students"/><Metric n={subjects.length} t="Subjects"/><Metric n={categories.length} t="Categories"/></div></section></div>
    </div>}

    {tab==='timetable'&&<section className="examio-panel"><div className="examio-panel-kicker">EXAMINATION SCHEDULE</div><h2>Build timetable</h2><p>Select a date, class, subject and time. Each class can have only one examination on a date.</p>{error&&<div className="examio-error">{error}</div>}<form onSubmit={addEntry} className="examio-timetable-form"><select required value={date} onChange={e=>setDate(e.target.value)}><option value="">Date</option>{days.map(d=><option key={d} value={d}>{formatDate(d)}</option>)}</select><select required value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select required value={subjectId} onChange={e=>setSubjectId(e.target.value)}><option value="">Subject</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input required type="time" value={startTime} onChange={e=>setStartTime(e.target.value)}/><input required type="time" value={endTime} onChange={e=>setEndTime(e.target.value)}/><button type="submit" className="examio-primary"><Plus/> Add</button></form><div className="examio-table-wrap"><table><thead><tr><th>Date</th><th>Class</th><th>Subject</th><th>Time</th><th>Action</th></tr></thead><tbody>{[...entries].sort((a,b)=>`${a.date}${a.startTime}`.localeCompare(`${b.date}${b.startTime}`)).map(x=><tr key={x.id}><td>{formatDate(x.date)}</td><td><b>{className(x.classId)}</b></td><td>{subjectName(x.subjectId)}</td><td>{x.startTime}–{x.endTime}</td><td><button type="button" className="examio-delete" onClick={()=>deleteTimetableEntry(uid,campus.id,exam.id,x.id)}><Trash2/></button></td></tr>)}{!entries.length&&<tr><td colSpan={5} className="examio-table-empty">No timetable entries yet.</td></tr>}</tbody></table></div></section>}

    {tab==='rooms'&&<section className="examio-panel"><div className="examio-panel-kicker">EXAMINATION ROOMS</div><h2>Rooms & layouts</h2><p>Rooms are examination-specific. Configure them here for <strong>{exam.name}</strong>; another examination can have a completely different room setup.</p><div className="mt-5"><RoomsView rooms={rooms} categories={categories} onSaveRoom={onSaveRoom} onDeleteRoom={onDeleteRoom} onDeleteBulkRooms={onDeleteBulkRooms}/></div></section>}

    {tab==='seating'&&<section className="examio-panel"><div className="examio-panel-kicker">SEATING GENERATOR</div><h2>Generate examination seating</h2><p>Seating sessions are created automatically from timetable entries with the same date and time. Only rooms configured for this examination are used.</p>{examSessions.length?<SeatingGeneratorView sessions={examSessions} students={students} classes={classes} categories={categories} rooms={rooms} arrangements={arrangements} onSaveArrangement={onSaveArrangement} onOpenPrintModal={onOpenPrintModal}/>:<div className="examio-empty"><Grid3X3/><h3>Create the timetable first</h3><p>Add at least one timetable entry. The corresponding examination session will then appear here.</p><button type="button" className="examio-primary" onClick={()=>setTab('timetable')}>Open Timetable</button></div>}</section>}

    {tab==='attendance'&&<section className="examio-panel"><div className="examio-panel-kicker">ATTENDANCE</div><h2>Attendance & absentee records</h2><p>Use the permanent student register and this examination's timetable to record attendance and absentees.</p><div className="grid grid-cols-1 md:grid-cols-3 gap-3 mt-5"><Metric n={students.length} t="Registered students"/><Metric n={classes.length} t="Participating classes"/><Metric n={examSessions.length} t="Exam sessions"/></div><div className="examio-work-list">{examSessions.length?examSessions.map(s=><div className="examio-work-row" key={s.id}><div><strong>{formatDate(s.date)}</strong><span className="block mt-1">{s.time} · {s.classConfigs.map(c=>className(c.classId)).join(', ')}</span></div><span className="examio-badge">Ready</span></div>):<div className="examio-table-empty">Attendance sessions will appear after the timetable is created.</div>}</div></section>}

    {tab==='duty'&&<section className="examio-panel"><div className="examio-panel-kicker">INVIGILATION</div><h2>Invigilation planning</h2><p>Invigilator assignment is based on the sessions and rooms configured for this examination.</p><div className="grid grid-cols-1 md:grid-cols-3 gap-3 mt-5"><Metric n={examSessions.length} t="Sessions requiring duty"/><Metric n={rooms.length} t="Rooms available"/><Metric n={categories.length} t="Exam categories"/></div><div className="examio-work-list">{examSessions.length?examSessions.map(s=><div className="examio-work-row" key={s.id}><div><strong>{formatDate(s.date)} · {s.time}</strong><span className="block mt-1">{rooms.length} rooms available · {s.classConfigs.length} classes</span></div><span className="examio-badge">Plan duty</span></div>):<div className="examio-table-empty">Create timetable sessions before assigning invigilation.</div>}</div><div className="examio-info-banner"><Info/><span>Teacher/invigilator assignment should be completed against these examination sessions rather than as permanent campus data.</span></div></section>}

    {tab==='reports'&&<section className="examio-panel"><div className="examio-panel-kicker">REPORT CENTRE</div><h2>Examination reports</h2><p>Generate or print reports from the data belonging to this examination.</p><div className="examio-report-grid"><ReportCard icon={CalendarDays} title="Timetable Report" text={`${entries.length} timetable entries`} onClick={()=>window.print()}/><ReportCard icon={DoorOpen} title="Room Report" text={`${rooms.length} examination rooms`} onClick={()=>window.print()}/><ReportCard icon={Grid3X3} title="Seating Report" text={`${arrangements.length} generated arrangements`} onClick={()=>window.print()}/><ReportCard icon={Users} title="Invigilation Report" text={`${examSessions.length} sessions`} onClick={()=>window.print()}/><ReportCard icon={ClipboardList} title="Attendance Report" text="Attendance data for this examination" onClick={()=>window.print()}/><ReportCard icon={FileText} title="Examination Summary" text={`${classes.length} classes · ${students.length} students`} onClick={()=>window.print()}/></div><div className="examio-info-banner"><Printer/><span>Use the report cards above to print the current examination workspace. Detailed export formats can be added without changing the stored examination data.</span></div></section>}
   </main>
  </div>
 </div>;
};

const Metric=({n,t}:{n:number|string;t:string})=><div className="examio-metric"><strong>{n}</strong><span>{t}</span></div>;
const Step=({n,title,active}:{n:string;title:string;active:boolean})=><div className={`examio-step ${active?'done':''}`}><b>{n}</b><span>{title}</span></div>;
const ReportCard=({icon:Icon,title,text,onClick}:{icon:any;title:string;text:string;onClick:()=>void})=><button type="button" className="examio-report-card text-left" onClick={onClick}><Icon/><h3>{title}</h3><p>{text}</p><span className="inline-flex items-center gap-1 mt-4 text-[10px] font-black text-cyan-700">Print report →</span></button>;
