import React, { useEffect, useMemo, useState } from 'react';
import { CalendarDays, ClipboardList, Grid3X3, Users, BarChart3, Plus, Trash2, ArrowLeft } from 'lucide-react';
import { Campus, Examination, ExamTimetableEntry } from '../types/tenant';
import { Category, ClassItem, Subject } from '../types';
import { deleteTimetableEntry, saveTimetableEntry, subscribeTimetable } from '../lib/tenant';

interface Props { uid:string; campus:Campus; exam:Examination; categories:Category[]; classes:ClassItem[]; subjects:Subject[]; onBack:()=>void; }

export const ExaminationWorkspace:React.FC<Props>=({uid,campus,exam,classes,subjects,onBack})=>{
 const [entries,setEntries]=useState<ExamTimetableEntry[]>([]); const [date,setDate]=useState(exam.startDate); const [classId,setClassId]=useState(''); const [subjectId,setSubjectId]=useState(''); const [startTime,setStartTime]=useState('09:00'); const [endTime,setEndTime]=useState('11:00'); const [tab,setTab]=useState<'overview'|'timetable'|'attendance'|'seating'|'duty'|'reports'>('overview');
 useEffect(()=>subscribeTimetable(uid,campus.id,exam.id,setEntries),[uid,campus.id,exam.id]);
 const subjectsForClass=useMemo(()=>subjects,[subjects]);
 const addEntry=async(e:React.FormEvent)=>{e.preventDefault();if(!classId||!subjectId)return;const id=crypto.randomUUID();await saveTimetableEntry(uid,campus.id,{id,examinationId:exam.id,date,classId,subjectId,startTime,endTime,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});};
 const className=(id:string)=>classes.find(c=>c.id===id)?.name||'Unknown class'; const subjectName=(id:string)=>subjects.find(s=>s.id===id)?.name||'Unknown subject';
 const days=useMemo(()=>{const out:string[]=[];let d=new Date(`${exam.startDate}T00:00:00`);const end=new Date(`${exam.endDate}T00:00:00`);while(d<=end){out.push(d.toISOString().slice(0,10));d.setDate(d.getDate()+1)}return out},[exam.startDate,exam.endDate]);
 return <div className="space-y-6"><div className="flex items-start gap-3"><button onClick={onBack} className="p-2 rounded-lg hover:bg-slate-100"><ArrowLeft className="w-5 h-5"/></button><div><p className="text-xs font-bold text-blue-600">{campus.name}</p><h1 className="text-2xl font-black text-slate-900">{exam.name}</h1><p className="text-xs text-slate-500">{exam.startDate} → {exam.endDate} · {exam.status}</p></div></div>
 <div className="flex gap-2 flex-wrap border-b border-slate-200 pb-2">{[['overview','Overview',BarChart3],['timetable','Timetable',CalendarDays],['attendance','Attendance',ClipboardList],['seating','Seating',Grid3X3],['duty','Invigilation',Users],['reports','Reports',BarChart3]].map(([id,label,Icon]:any)=><button key={id} onClick={()=>setTab(id)} className={`px-3 py-2 rounded-lg text-xs font-bold flex items-center gap-2 ${tab===id?'bg-slate-900 text-white':'text-slate-600 hover:bg-slate-100'}`}><Icon className="w-4 h-4"/>{label}</button>)}</div>
 {tab==='overview'&&<div className="grid md:grid-cols-4 gap-4"><div className="bg-white p-5 border rounded-2xl"><div className="text-2xl font-black">{entries.length}</div><div className="text-xs text-slate-500">Timetable entries</div></div><div className="bg-white p-5 border rounded-2xl"><div className="text-2xl font-black">{new Set(entries.map(x=>x.classId)).size}</div><div className="text-xs text-slate-500">Classes scheduled</div></div><div className="bg-white p-5 border rounded-2xl"><div className="text-2xl font-black">{new Set(entries.map(x=>x.subjectId)).size}</div><div className="text-xs text-slate-500">Subjects scheduled</div></div><div className="bg-white p-5 border rounded-2xl"><div className="text-2xl font-black">{days.length}</div><div className="text-xs text-slate-500">Exam days</div></div></div>}
 {tab==='timetable'&&<div className="space-y-5"><div className="bg-white border rounded-2xl p-5"><h2 className="font-black">Assign a subject to a class and date</h2><form onSubmit={addEntry} className="grid md:grid-cols-5 gap-3 mt-4"><select value={date} onChange={e=>setDate(e.target.value)} className="border rounded-xl px-3 py-2.5 text-sm"><option value="">Date</option>{days.map(d=><option key={d}>{d}</option>)}</select><select required value={classId} onChange={e=>setClassId(e.target.value)} className="border rounded-xl px-3 py-2.5 text-sm"><option value="">Class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select required value={subjectId} onChange={e=>setSubjectId(e.target.value)} className="border rounded-xl px-3 py-2.5 text-sm"><option value="">Subject</option>{subjectsForClass.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input type="time" value={startTime} onChange={e=>setStartTime(e.target.value)} className="border rounded-xl px-3 py-2.5 text-sm"/><button className="bg-blue-600 text-white rounded-xl font-bold text-sm flex items-center justify-center gap-2"><Plus className="w-4 h-4"/> Add</button></form><p className="text-[11px] text-slate-400 mt-2">Subjects are selected from this campus's permanent subject master. Class-specific curriculum filtering can be enabled next.</p></div><div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50 text-xs"><tr><th className="text-left p-3">Date</th><th className="text-left p-3">Class</th><th className="text-left p-3">Subject</th><th className="text-left p-3">Time</th><th className="p-3"/></tr></thead><tbody>{entries.sort((a,b)=>`${a.date}${a.startTime}`.localeCompare(`${b.date}${b.startTime}`)).map(x=><tr key={x.id} className="border-t"><td className="p-3">{x.date}</td><td className="p-3 font-semibold">{className(x.classId)}</td><td className="p-3">{subjectName(x.subjectId)}</td><td className="p-3">{x.startTime}–{x.endTime}</td><td className="p-3 text-right"><button onClick={()=>deleteTimetableEntry(uid,campus.id,exam.id,x.id)} className="text-rose-600"><Trash2 className="w-4 h-4"/></button></td></tr>)}{entries.length===0&&<tr><td colSpan={5} className="p-10 text-center text-slate-400">No timetable entries yet.</td></tr>}</tbody></table></div></div>}
 {tab!=='overview'&&tab!=='timetable'&&<div className="bg-white border rounded-2xl p-10 text-center"><h2 className="font-black text-lg">{tab==='attendance'?'Attendance / Absentees':tab==='seating'?'Seating Generator':tab==='duty'?'Invigilation':'Reports'}</h2><p className="text-sm text-slate-500 mt-2">This examination workspace is ready. The existing Examio modules will be connected to this examination context in the next migration step.</p></div>}
 </div>;
};
